import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/components/SideBar";
import Chart from "@/components/Chart";
import { FaRegUserCircle } from "react-icons/fa";
import { RiArrowDropDownLine } from "react-icons/ri";
import OverviewChart from "@/components/OverviewChart";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [collapsed, setCollapsed] = useState(false);

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Sidebar collapsed={collapsed} toggleCollapsed={toggleCollapsed} />

        <div className={styles.board}>
         <Nav />

          <div className={styles.boardContent}>
            <div className={styles.view}>
              <h2>Sales overview</h2>
              <div className={styles.salesOverview}>
                <div className={styles.overviewContent}>
                  <h5>Today&apos;s sales</h5>
                  <p>₦1,652.50</p>
                </div>

                <div className={styles.overviewContentActive}>
                  <h5>24 Aug - 01 Sep 21</h5>
                  <OverviewChart />
                  <h4>This Week</h4>
                  <p>₦1,652.50</p>
                </div>
                <div className={styles.overviewContent}>
                  <h4>24 Aug - 01 Sep 21</h4>
                  <OverviewChart />
                  <h4>This Month</h4>
                  <p>₦1,652.50</p>
                </div>
                <div className={styles.overviewContent}>
                  <h5>24 Aug - 01 Sep 21</h5>
                  <OverviewChart />
                  <h4>This Month</h4>
                  <p>₦1,652.50</p>
                </div>
              </div>
            </div>
            <div className={styles.boardBottom}>
              <div className={styles.graph}>
                <div className={styles.graphTop}>
                  <h4>Sales</h4>
                  <span>7 days</span>
                  <span>30 days</span>
                  <select name="" id="">
                    <option value="">USD</option>
                    <option value="">NGN</option>
                  </select>
                  <div className={styles.email}>
                    <input type="email" placeholder="Email" />
                    <RiArrowDropDownLine className={styles.profileIcon} />
                  </div>
                  <button>
                    <RiArrowDropDownLine className={styles.profileIcon} />
                    Download Report
                  </button>
                </div>
                <div className={styles.line}>
                  <Chart />
                </div>
              </div>

              <div className={styles.wire}>
                <p>
                  KlashaWire - send money to businesses globally from Africa
                </p>
                <button>Send a wire</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
